#ifdef SHADER_CONSTANTS_LITERAL
#define SHADER_CONST(NAME, INDEX) R"(const int )" #NAME " = " #INDEX ";\n"
#else
#define SHADER_CONST(NAME, INDEX) \
    constexpr int NAME = INDEX;
#endif

/** Uber2D Modes */
SHADER_CONST(UBER2D_MODE_TEXTURE, 0)
SHADER_CONST(UBER2D_MODE_HAZE, 1)
SHADER_CONST(UBER2D_MODE_BACK_BLUR, 2)
SHADER_CONST(UBER2D_MODE_GLOW, 3)
SHADER_CONST(UBER2D_MODE_DISINTEGRATE, 4)
SHADER_CONST(UBER2D_MODE_DISINTEGRATE_PLASMA, 5)

/** Uber3D Modes */
SHADER_CONST(UBER3D_MODE_BASIC, 0)
SHADER_CONST(UBER3D_MODE_LEVEL, 1)

/** Uber3D Limits */
SHADER_CONST(UBER3D_MODEL_COUNT, 64)

/** HUD Modes */
SHADER_CONST(HUD_MODE_BORDER_DASHED, 0)
SHADER_CONST(HUD_MODE_BUTTON, 1)

#undef SHADER_CONST