#ifdef SHARED_CONSTANTS_LITERAL
    #define SHARED_CONST(NAME, INDEX) R"(const int )" #NAME " = " #INDEX ";\n"
    #define SHARED_CONSTU(NAME, INDEX) R"(const uint )" #NAME " = " #INDEX ";\n"
#else
    #include <cstdint>
    #define SHARED_CONST(NAME, INDEX) \
        constexpr int32_t NAME = INDEX;
    #define SHARED_CONSTU(NAME, INDEX) \
        constexpr uint32_t NAME = INDEX;
#endif

#if defined(SHARED_CONSTANTS_LITERAL)
    #define SHARED_CONSTANTS_FORCE
#endif

#if defined(SHARED_CONSTANTS_FORCE) || !defined(SHARED_CONSTANTS_GUARD)

/* Common Constants */
SHARED_CONSTU(DIRECTION_BIT_NORTH, 0)
SHARED_CONSTU(DIRECTION_BIT_EAST, 1)
SHARED_CONSTU(DIRECTION_BIT_SOUTH, 2)
SHARED_CONSTU(DIRECTION_BIT_WEST, 3)

/* Tile Edge Flags */
SHARED_CONSTU(TILE_EDGE_NORTH_BITS, 286331153)

SHARED_CONSTU(TILE_EDGE_WALL_BIT, 1 << 0)
SHARED_CONSTU(TILE_EDGE_WALL_EAST_BIT, 1 << 1)
SHARED_CONSTU(TILE_EDGE_WALL_SOUTH_BIT, 1 << 2)
SHARED_CONSTU(TILE_EDGE_WALL_WEST_BIT, 1 << 3)
SHARED_CONSTU(TILE_EDGE_DOOR_BIT, 1 << 4)
SHARED_CONSTU(TILE_EDGE_DOOR_EAST_BIT, 1 << 5)
SHARED_CONSTU(TILE_EDGE_DOOR_SOUTH_BIT, 1 << 6)
SHARED_CONSTU(TILE_EDGE_DOOR_WEST_BIT, 1 << 7)

/* Tile Flags */
SHARED_CONSTU(TILE_NONE_BIT, 1 << 0)
SHARED_CONSTU(TILE_FLOOR_BIT, 1 << 1)
SHARED_CONSTU(TILE_HOLE_BIT, 1 << 2)

/* Tile Special Flags */
SHARED_CONSTU(TILE_SPECIAL_VISITED_BIT, 1 << 0)

/* Level Constants */
SHARED_CONST(MAX_LEVEL_WIDTH, 32)
SHARED_CONST(MAX_LEVEL_HEIGHT, 32)
SHARED_CONST(MAX_LEVEL_TILE_COUNT, (MAX_LEVEL_WIDTH * MAX_LEVEL_HEIGHT))

/* Uber2D Modes */
SHARED_CONST(UBER2D_MODE_TEXTURE, 0)
SHARED_CONST(UBER2D_MODE_HAZE, 1)
SHARED_CONST(UBER2D_MODE_BACK_BLUR, 2)
SHARED_CONST(UBER2D_MODE_GLOW, 3)
SHARED_CONST(UBER2D_MODE_DISINTEGRATE, 4)
SHARED_CONST(UBER2D_MODE_DISINTEGRATE_PLASMA, 5)

/* Uber3D Modes */
SHARED_CONST(UBER3D_MODE_BASIC, 0)
SHARED_CONST(UBER3D_MODE_LEVEL, 1)

/* Uber3D Limits */
SHARED_CONST(UBER3D_MODEL_COUNT, 64)

/* HUD Modes */
SHARED_CONST(HUD_MODE_BORDER_DASHED, 0)
SHARED_CONST(HUD_MODE_BUTTON, 1)
SHARED_CONST(HUD_MODE_MAP, 2)

    #if !defined(SHARED_CONSTANTS_FORCE) && !defined(SHARED_CONSTANTS_GUARD)
        #define SHARED_CONSTANTS_GUARD 1
    #endif

#endif

#undef SHARED_CONST
#undef SHARED_CONSTU
